### ISSUE TITLE
NPE Error when installing Identity OAuth API on XWiki 15.x

### ISSUE THREAD

**Issue by oanalavinia** [xwikisas/identity-oauth#37]
Environment: local instance of XWiki 15.5.2 on HSQLDB, Jetty, Java 11 , Identity OAuth API 1.7.1

STEPS TO REPRODUCE

1. Start an instance of XWiki 15.5.2
2. Install Identity OAuth API (tested with 1.7.1)
3. Observe the XWiki console

EXPECTED RESULTS

No errors/ warnings are displayed.

ACTUAL RESULTS

Near the moment when the installation process is finished, the following NPE Error is encountered:

```
2023-10-03 17:51:35,518 [extension/wiki:xwiki job group daemon thread - org.xwiki.extension.job.internal.InstallJob@67e262a5([extension, action, com.xwiki.identity-oauth:identity-oauth-ui, wiki:xwiki])] ERROR .o.i.DefaultObservationManager - Failed to send event [org.xwiki.job.event.JobFinishedEvent@1a7db994] to listener [com.xpn.xwiki.XWiki@5476787b] 
java.lang.NullPointerException: null
	at com.xpn.xwiki.XWiki.onJobFinished(XWiki.java:7905)
	at com.xpn.xwiki.XWiki.onEvent(XWiki.java:7862)
	at org.xwiki.observation.internal.DefaultObservationManager.notify(DefaultObservationManager.java:338)
	at org.xwiki.observation.internal.DefaultObservationManager.notify(DefaultObservationManager.java:303)
	at org.xwiki.job.AbstractJob.jobFinished(AbstractJob.java:338)
	at org.xwiki.extension.job.internal.AbstractExtensionJob.jobFinished(AbstractExtensionJob.java:134)
	at org.xwiki.job.AbstractJob.runInContext(AbstractJob.java:251)
	at org.xwiki.job.AbstractJob.run(AbstractJob.java:223)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

After installing this module, every application install will throw this error in the XWiki console

**Comment by oanalavinia** [comment]
This issue was fixed in the XWiki platform as part of https://jira.xwiki.org/browse/XWIKI-21497 for XWiki versions `15.5.4, 15.9, 15.10-rc1`
