### ISSUE TITLE
Login not working starting with XWiki 15.9

### ISSUE THREAD

**Issue by oanalavinia** [xwikisas/identity-oauth#41]
For reproducing I used an existing provider https://github.com/xwikisas/integration-azure-oauth.

**Steps to reproduce:**
1. Configure the provider. On my case I followed the documentation for the Azure AD provider https://store.xwiki.com/xwiki/bin/view/Extension/MicrosoftAzureSSO/
2. Go to an incognito browser and try to login using the Azure AD option
3. Complete the Azure login steps

**Expected result:**
After completing the login process, you are redirected to the home page, logged in with the Azure user

**Actual result:**
After completing the login process, you are redirected to the home page, but you are still logged out

**Investigation:**
This issue is a consequence of https://jira.xwiki.org/browse/XWIKI-542 . Before it, the `xwiki.authentication.encryptionKey` xwiki.cfg property had a default value, but now it does not have a value defined and it's causing this problem.
The idea of this issue is to make sure that an automatically generated key is used in case there isn't one defined in xwiki.cfg. The quick **solution / workaround** is to define the `xwiki.idoauth.encryptionKey` or `xwiki.authentication.encryptionKey` property (check https://www.xwiki.org/xwiki/bin/view/Documentation/AdminGuide/Authentication/#HAuthenticationparameters )

**Comment by oanalavinia** [comment]
Related server logs:
```
java.lang.RuntimeException: Failed to get [role = [class com.xwiki.identityoauth.internal.IdentityOAuthAuthService] hint = [default]]
	at org.xwiki.component.embed.GenericProvider.get(GenericProvider.java:103)
	at wiki:xwiki//com.xwiki.identityoauth.internal.DefaultIdentityOAuthManager.tryInittingAuthService(DefaultIdentityOAuthManager.java:160)
	at wiki:xwiki//com.xwiki.identityoauth.internal.DefaultIdentityOAuthManager.startIfNeedBe(DefaultIdentityOAuthManager.java:137)
	at wiki:xwiki//com.xwiki.identityoauth.internal.DefaultIdentityOAuthManager.reloadConfig(DefaultIdentityOAuthManager.java:253)
	at wiki:xwiki//com.xwiki.identityoauth.internal.IdentityOAuthEventListener.onEvent(IdentityOAuthEventListener.java:108)
	at org.xwiki.observation.internal.DefaultObservationManager.notify(DefaultObservationManager.java:338)
	at org.xwiki.observation.internal.DefaultObservationManager.notify(DefaultObservationManager.java:303)
	at com.xpn.xwiki.internal.XWikiInitializerJob.runInternal(XWikiInitializerJob.java:117)
	at org.xwiki.job.AbstractJob.runInContext(AbstractJob.java:246)
	at org.xwiki.job.AbstractJob.run(AbstractJob.java:223)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.xwiki.component.manager.ComponentLookupException: Failed to lookup component [com.xwiki.identityoauth.internal.IdentityOAuthAuthService] identified by type [class com.xwiki.identityoauth.internal.IdentityOAuthAuthService] and hint [default]
	at org.xwiki.component.embed.EmbeddableComponentManager.getInstance(EmbeddableComponentManager.java:332)
	at org.xwiki.component.embed.EmbeddableComponentManager.getInstance(EmbeddableComponentManager.java:317)
	at org.xwiki.component.embed.GenericProvider.getInstance(GenericProvider.java:111)
	at org.xwiki.component.embed.GenericProvider.get(GenericProvider.java:100)
	... 10 common frames omitted
Caused by: org.xwiki.component.manager.ComponentLookupException: Failed to lookup component [com.xwiki.identityoauth.internal.CookieAuthenticationPersistence] identified by type [class com.xwiki.identityoauth.internal.CookieAuthenticationPersistence] and hint [default]
	at org.xwiki.component.embed.EmbeddableComponentManager.getInstance(EmbeddableComponentManager.java:332)
	at org.xwiki.component.embed.EmbeddableComponentManager.getInstance(EmbeddableComponentManager.java:317)
	at org.xwiki.component.embed.EmbeddableComponentManager.getDependencyInstance(EmbeddableComponentManager.java:591)
	at org.xwiki.component.embed.EmbeddableComponentManager.createInstance(EmbeddableComponentManager.java:540)
	at org.xwiki.component.embed.EmbeddableComponentManager.getComponentInstance(EmbeddableComponentManager.java:636)
	at org.xwiki.component.embed.EmbeddableComponentManager.getInstance(EmbeddableComponentManager.java:329)
	... 13 common frames omitted
Caused by: com.xwiki.identityoauth.IdentityOAuthException: Unable to initialize ciphers
	at wiki:xwiki//com.xwiki.identityoauth.internal.CookieAuthenticationPersistence.initialize(CookieAuthenticationPersistence.java:138)
	at org.xwiki.component.embed.InitializableLifecycleHandler.handle(InitializableLifecycleHandler.java:39)
	at org.xwiki.component.embed.EmbeddableComponentManager.createInstance(EmbeddableComponentManager.java:550)
	at org.xwiki.component.embed.EmbeddableComponentManager.getComponentInstance(EmbeddableComponentManager.java:636)
	at org.xwiki.component.embed.EmbeddableComponentManager.getInstance(EmbeddableComponentManager.java:329)
	... 18 common frames omitted
Caused by: com.xwiki.identityoauth.IdentityOAuthException: Unable to initialize cipher.
	at wiki:xwiki//com.xwiki.identityoauth.internal.CookieAuthenticationPersistence.getCipher(CookieAuthenticationPersistence.java:197)
	at wiki:xwiki//com.xwiki.identityoauth.internal.CookieAuthenticationPersistence.initialize(CookieAuthenticationPersistence.java:135)
	... 22 common frames omitted

```
